<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lemon</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Lemon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(%\w+)(?:\s+(\w+))?\s*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.action.begin.lemon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.action.end.lemon</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c#block_innards</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.c++#block_innards</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+)(?:(\()(\w+)(\)))?\s*(::=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.non-terminal.lhs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.action.begin</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.destination</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.variable.action.end</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rule.start</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.righthand</string>
			<key>end</key>
			<string>\s*(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.rule.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\s+</string>
					<key>name</key>
					<string>meta.whitespace</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.terminal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.variable.action.begin</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.source.terminal</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.variable.action.end</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Z0-9_]+)(?:(\()(\w+)(\)))?</string>
					<key>name</key>
					<string>meta.terminal</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.non-terminal</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.variable.action.begin</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.source.non-terminal</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.variable.action.end</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([a-z0-9_]+)(?:(\()(\w+)(\)))?</string>
					<key>name</key>
					<string>meta.non-terminal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c#block_innards</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c++#block_innards</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lemon</string>
	<key>uuid</key>
	<string>D3409973-B84B-456F-967D-85FED99C8FC4</string>
</dict>
</plist>
